// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ItemBook","status":true,"description":"Displays detailed statuses of items.","parameters":{"Unknown Data":"??????","Price Text":"Price","Equip Text":"Equip","Type Text":"Type"}},
{"name":"EnemyBook","status":true,"description":"Displays detailed statuses of enemies.","parameters":{"Unknown Data":"??????"}},
{"name":"SimpleMsgSideView","status":true,"description":"at sideview battle, only display item/skill names.","parameters":{"displayAttack":"0","position":"1"}},
{"name":"CurrentTargetToVariable","status":true,"description":"Stores the current target's id in a designated variable","parameters":{"variableNumber":"6"}},
{"name":"NameBar","status":true,"description":"Adds a nameplate above message boxes.","parameters":{"variable":"34"}},
{"name":"NoEnemyListing","status":true,"description":"Suppresses the enemies list that appears pre-battle","parameters":{}},
{"name":"skillsOnlyBattleWindow","status":true,"description":"Shows only a listing of all an actor's skills in the\r\nactor command window","parameters":{"showAttackCommand":"1"}},
{"name":"ManyAccessories","status":true,"description":"Equip more than one accessory","parameters":{"accessoryCount":"3"}},
{"name":"RenameAttackPerWeapon","status":true,"description":"Weapons can rename the Attack skill","parameters":{}},
{"name":"CommonEventAtBattleStart","status":true,"description":"Calls common events during battle","parameters":{"battleStartEventID":"17","battleWinEventID":"20","battleEscapeEventID":"20","partyWipeEventID":"-1","turnStartEventID":"21","turnEndEventID":"-1","actionEndEventID":"-1"}},
{"name":"wasdmove","status":true,"description":"Enables movement with the WASD keys.","parameters":{}},
{"name":"NoMPMoreStatusIcons","status":true,"description":"Removes MP bar, making room for more status icons","parameters":{}},
{"name":"TLRMenu","status":true,"description":"A very simple alternate menu. Designed for Trample Line Riddles.","parameters":{}}
];
